{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "359932a4_fa85535e",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 10
      },
      "lineNbr": 0,
      "author": {
        "id": 29350
      },
      "writtenOn": "2022-09-30T17:18:44Z",
      "side": 1,
      "message": "I have fixed the problem that cannot be activated to allow network data access.",
      "revId": "6db691b57ed61b7b2ee130d861bab92c26ba3a03",
      "serverId": "1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71"
    }
  ]
}